M48
; DRILL file {KiCad 6.0.7+dfsg-1build1} date Sun 19 Feb 2023 10:12:34 AM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-19T10:12:34-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1build1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X10.1394Y-3.1047
X10.1394Y-3.6047
T0
M30
